
spring:
  application:
    name: foo
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    password: postgres
    username: Password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8050

  servlet:
    context-path: /product

